version: '3.7'
services:
  spring:
    container_name: spring
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: hobby_db
      MYSQL_USER: hobby_user
      MYSQL_PASSWORD: hobby_pass
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter
    command:
      - "--mysqld.username=hobby_user:hobby_pass"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      - mysql
