version: '3.7'
services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    volumes:
      - ./script.js:/script.js
    command: run /script.js
    networks:
      - hobby-adventure_default

networks:
  hobby-adventure_default:
    external: true
