version: '3.7'
services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    volumes:
      - .:/scripts
    command: run /scripts/explorations-thumbnail.js -o experimental-prometheus-rw --system-tags method,status
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://host.docker.internal:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=med,p(95)
      - "TESTID=${TESTID:?TESTID를 설정해주세요. 예: TESTID=$(date +%Y%m%d-%H%M%S) docker compose up}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hobby-adventure_default

networks:
  hobby-adventure_default:
    external: true
